# Generated by Django 4.1.6 on 2023-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('Employee_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Contact_Number', models.IntegerField()),
                ('Emergency_Contact_Number', models.IntegerField()),
                ('Address', models.TextField()),
                ('Postion', models.CharField(max_length=250)),
                ('DOB', models.DateField()),
                ('Martial_status', models.BooleanField(default=False)),
                ('Blood_Group', models.CharField(max_length=10)),
                ('Job_Title', models.CharField(max_length=250)),
                ('work_Location', models.CharField(max_length=250)),
                ('Date_of_Joining', models.DateField(auto_now=True)),
                ('Reporting_to', models.CharField(max_length=250)),
                ('Linked_In', models.URLField(max_length=250)),
                ('Profile_Picture', models.ImageField(blank=True, upload_to='media/profile')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
