# Generated by Django 4.1.5 on 2023-02-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_leaveapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='number_Of_Days',
        ),
    ]
