# Generated by Django 4.1.5 on 2023-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_leaveapplication_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='emp_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
