# Generated by Django 4.1.5 on 2023-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_leaveapplication_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='emp_id',
            new_name='emp_name',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='number_Of_Days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
