# Generated by Django 4.1.5 on 2023-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_emp_id_leaveapplication_emp_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='number_Of_Days',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='emp_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
