# Generated by Django 4.1.5 on 2023-02-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_employeemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='user',
        ),
    ]
