# Generated by Django 4.1.5 on 2023-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_employeemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
    ]
