# Generated by Django 4.1.5 on 2023-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_leaveapplication_nature_of_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='first_Day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='last_Day',
            field=models.DateField(null=True),
        ),
    ]
