# Generated by Django 4.1.5 on 2023-02-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_alter_leaveapplication_first_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='number_Of_Days',
            field=models.IntegerField(null=True),
        ),
    ]
